apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: gmacastil/microdb
    sonarqube.org/project-key: microdb
  description: Aplicación Java para gestión de base de datos; utiliza Spring Boot
  name: microdb
  tags:
  - java
  - springboot
spec:
  lifecycle: production
  owner: gmacastil
  system: dummy
  type: service
