apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: microdb
  description: Aplicación Java para gestión de base de datos; utiliza Spring Boot
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: gmacastil/microdb
    sonarqube.org/project-key: microdb
  tags:
    - java
    - springboot
spec:
  type: service
  owner: gmacastil
  lifecycle: production
  system: discovery
  providesApis:
