apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: microdb
  description: Aplicaci贸n Java para gesti贸n de base de datos; utiliza Spring Boot
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: gmacastil/microdb
    sonarqube.org/project-key: microdb
  tags:
    - java
    - springboot
spec:
  type: service
  owner: gmacastil
  lifecycle: production
  system: discovery
  providesApis:
    - microdb-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: microdb-api
  description: Aplicaci贸n Java para gesti贸n de base de datos; utiliza Spring Boot
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - java
    - springboot
spec:
  type: openapi
  owner: gmacastil
  lifecycle: production
  system: discovery
  definition: 
    $text: /docs/openapi.yaml